### ISSUE TITLE
Useless constant max_days

### ISSUE THREAD

**Issue by Fenrir7Asteron** [theMavl/LMS-Review#1]
1. Design decision
Bogdan Fedotov: If you are not going to use max_days in other places besides line #15, delete it and just pass 1.

https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/forms.py#L3

**Comment by theMavl** [comment]
This is an initialisation of variable, which is being overrided here:
https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/views/document/renew_document.py#L41
by the value received from this https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/views/document/renew_document.py#L31

**Comment by Fenrir7Asteron** [comment]
Okay.
