### ISSUE TITLE
Lack of comments in the code

### ISSUE THREAD

**Issue by thisisbeka** [theMavl/LMS-Review#10]
It is hard to understand what's going on. Dear programmer, please add comments in  your code. (it's more as an advice because I didn't find anything to comment to be honest without your comments it's ununderstandable)

**Comment by theMavl** [comment]
From my point of view, the code is self-documenting, so it would be better if you point on particular parts that are not understandable
Perhaps class diagram included to this snapshot will help you to understand what's happening
