### ISSUE TITLE
Imports issue

### ISSUE THREAD

**Issue by Fenrir7Asteron** [theMavl/LMS-Review#2]
1. Design decisions
Bogdan Fedotov: There is no reason to import from django.http in two lines. You can combine lines 2 and 8. Also there is a tearing of imports. Firstly you have imports from django, then from library, then from django again. You can shift last imports from django up. 

https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/views/document/renew_document.py#L1-L9

**Comment by theMavl** [comment]
Noted, to be fixed
