### ISSUE TITLE
Unlogical name of a variable

### ISSUE THREAD

**Issue by Fenrir7Asteron** [theMavl/LMS-Review#4]
6. Programming style, names.
Bogdan Fedotov: This variable 'data' is obviously should be named 'date', isn't it?

https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/forms.py#L9
https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/forms.py#L11
https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/forms.py#L15

**Comment by theMavl** [comment]
Noted, to be fixed
