### ISSUE TITLE
What are the objects?

### ISSUE THREAD

**Issue by AmadeyKuspakov** [theMavl/LMS-Review#5]
https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/views/document/renew_document.py#L17
In the class GiveOut haven't found variable with name objects.

**Comment by theMavl** [comment]
This is a shortcut for `SELECT * FROM GiveOut WHERE id==id` provided by Django
As the result, variable `giveout` stores an instance of model GiveOut, fetched and deserialized from database, which has specified id
