### ISSUE TITLE
It is not clear from the code. Document renews since today or since it’s expire date

### ISSUE THREAD

**Issue by rsolovev** [theMavl/LMS-Review#8]
https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/forms.py#L2

**Comment by theMavl** [comment]
https://github.com/theMavl/LMS-Review/blob/2edea403b71239ae415b0a37ed957458dd6c6880/library/forms.py#L15
