### ISSUE TITLE
Interface is at bare minimum, e.g. at renew_details.html

### ISSUE THREAD

**Issue by kckusal** [theMavl/LMS-Review#9]
## Description
The user interface implemented in renew_details.html (haven't checked other files, there maybe too) is at a bare minimum. A regular user of this page, a librarian in this case, would need to frequent this page as there's likely to be a fair amount of renew requests. The minimal interface as is here will undoubtedly bore the user and is likely to have a negative impact on their productivity.

## Suggestions
More styling can be used in existing elements, and more user-friendly, interactive elements (e.g. animated tooltips) can be added to further improve the quality of displayed information and provide an engaging user experience.
The interface also seems to lack **proper navigation**. It is wise to provide more navigation controls like _Home_ or _Dashboard_ links (depending on your app structure) in every webpage.

**Comment by theMavl** [comment]
All user interface pages use generic base template. Base template is not a part of renewal system, so I did not include it in this frozen piece.
This is how `renew_details.html` actually looks:
![default](https://user-images.githubusercontent.com/13888156/38869790-7c01fc00-4254-11e8-9b5a-c84a6f574f82.png)
